# Generated by Django 3.1 on 2021-02-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='pdf',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(default='maths', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(default='', upload_to='')),
                ('studymaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='api.studymaterial')),
            ],
        ),
    ]
