# Generated by Django 3.1.2 on 2021-02-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='chapter',
            field=models.CharField(default='maths', max_length=50),
            preserve_default=False,
        ),
    ]
